# Generated by Django 4.0.5 on 2022-06-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_data', '0002_testdata_question_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255, verbose_name='Название факультета')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_kind', models.IntegerField(choices=[('1', 'Курсант'), ('2', 'Переменный состав')], verbose_name='Вид сотрудника')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_data.course', verbose_name='Курс')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_data.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'TestDataFirst',
                'verbose_name_plural': 'TestDataFirst',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_name', models.CharField(max_length=255, verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Subdivision',
                'verbose_name_plural': 'Subdivisions',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'TestResult',
                'verbose_name_plural': '4 TestResults',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='TestDataFirst',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',), 'verbose_name': 'Answer', 'verbose_name_plural': '3 Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',), 'verbose_name': 'Question', 'verbose_name_plural': '2 Questions'},
        ),
        migrations.AlterModelOptions(
            name='testdata',
            options={'ordering': ('id',), 'verbose_name': 'TestData', 'verbose_name_plural': '1 TestsData'},
        ),
        migrations.AddField(
            model_name='testresult',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_data.answer', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_data.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='questionary_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_data.questionarydata', verbose_name='Данные анкеты'),
        ),
        migrations.AddField(
            model_name='questionarydata',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_data.subdivision', verbose_name='Подразделение'),
        ),
    ]
