# Generated by Django 4.0.5 on 2022-06-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_data', '0003_course_faculty_questionarydata_subdivision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_kind', models.CharField(max_length=255, verbose_name='Вид сотрудника')),
            ],
            options={
                'verbose_name': 'EmployeeKind',
                'verbose_name_plural': 'EmployeeKinds',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='questionarydata',
            name='employee_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_data.employeekind', verbose_name='Тип сотрудника'),
        ),
    ]
