# Generated by Django 3.2.13 on 2022-06-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_data', '0004_auto_20220621_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('index_number',), 'verbose_name': 'Question', 'verbose_name_plural': '2 Questions'},
        ),
        migrations.AddField(
            model_name='questionarydata',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_data.testdata', verbose_name='Тест'),
        ),
    ]
